#!/usr/bin/python3
f = open("show_version.txt")
data = f.read()
data_bin = data.split("\n")
print("[Without Context Manager]")
print(f"Data type: {type(data)}")
print("Printing first line: ")
print("-" * 80)
print(data_bin[0])
print("-" * 80)
print()
f.close()
print("[With Context Manager]")
with open("show_version.txt") as f:
    data = f.readlines()
    print(f"Data type: {type(data)}")
    print("Printing first line: ")
    print("-" * 80)
    print(data[0].strip())
    print("-" * 80)
